version: '2.1'
orbs:
  android: circleci/android@2.0
jobs:
  test-apk:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
      - checkout
      - run:
                  name: "Install Firebase CLI"
                  command: |
                          curl -sL firebase.tools | bash
      - run:
            name: "Install fastlane"
            command: bundle check || bundle install --path vendor/bundle
      - run:
            name: "build"
            command: ./gradlew assembleDebug
      - run:
            name: "Deploy build to Firebase"
            command:
              bundle exec fastlane beta
                    branch:"master" app_id:$FIREBASE_APP_ID firebase_token:$FIREBASE_TOKEN

workflows:
  test-apk:
    jobs:
      - test-apk
