- name: CI
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          app_id: ${{secrets.FIREBASE_APP_ID}}
          firebase_token: ${{secrets.FIREBASE_TOKEN}}
          app_file: app/debug/app-debug.apk
          tester_groups: test-team